SET LINESIZE 200
SET PAGESIZE 100
SET TRIMOUT ON
SET TRIMSPOOL ON

COLUMN TABLE_NAME FORMAT A30 HEADING "Table Name"
COLUMN LAST_ANALYZED FORMAT A20 HEADING "Last Analyzed"
COLUMN STALE_STATS FORMAT A10 HEADING "Stale Stats"

SELECT
    OWNER,
    TABLE_NAME,
    TO_CHAR(LAST_ANALYZED, 'YYYY-MM-DD HH24:MI:SS') AS LAST_ANALYZED,
    CASE
        WHEN STALE_STATS = 'YES' THEN 'Stale'
        ELSE 'Not Stale'
    END AS STALE_STATS
FROM
    DBA_TAB_STATISTICS
WHERE
    TABLE_NAME IN ('GL_ARC_HEADERS_CSI_2020',
                   'GL_ARC_HEADERS_CSI_2021',
                   'GL_ARC_HEADERS_CSI_2022',
                   'GL_CODE_COMBINATIONS',
                   'GL_JE_HEADERS',
                   'GL_JE_LINES',
                   'XXBRKACCT',
                   'XXBRK_ACCT_TYPE',
                   'XXGLARC_GL_JE_LINES_TEST_MV')
ORDER BY
    OWNER,
    TABLE_NAME;
